### PR TITLE
Rmarkdown conflict

### PR DESCRIPTION
**Pull request by fmannhardt**
Rename parse and parsel to parse_trace and parsel_trace to avoid name clash with R base package. See #6

### CODE REVIEW

**Comment by fmannhardt** [comment]
It would be great if you could push this to CRAN since I want to use rmarkdown very soon in a workshop and this problem makes things difficult.

**Comment by gertjanssenswillen** [comment]
Thx. I'll send it to CRAN right away.

**Comment by gertjanssenswillen** [comment]
It's on its way to CRAN

**Comment by fmannhardt** [comment]
Thanks a lot.

--
Felix

________________________________

**Pull request merged**
